from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException

from ..auth import require_api_key
from ..config import get_settings
from ..models import ApiKey
from ..voices import VOICES, VOICES_BY_ID

router = APIRouter(tags=["voices"])

# Committed preview mp3s (generated by backend/scripts/generate_voice_previews.py).
PREVIEWS_DIR = Path(__file__).resolve().parent.parent / "static" / "voice_previews"


def _with_preview(voice: dict[str, Any]) -> dict[str, Any]:
    """Fill preview_audio_url when the voice's sample file exists on disk."""
    if not (PREVIEWS_DIR / f"{voice['voice_id']}.mp3").is_file():
        return voice
    base = get_settings().public_api_url.rstrip("/")
    return {
        **voice,
        "preview_audio_url": f"{base}/static/voice_previews/{voice['voice_id']}.mp3",
    }


@router.get("/list-voices")
async def list_voices(api_key: ApiKey = Depends(require_api_key)):
    return [_with_preview(v) for v in VOICES]


@router.get("/get-voice/{voice_id}")
async def get_voice(voice_id: str, api_key: ApiKey = Depends(require_api_key)):
    voice = VOICES_BY_ID.get(voice_id)
    if voice is None:
        raise HTTPException(404, detail="Voice not found")
    return _with_preview(voice)
