{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "architeq.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    kubernetes.io/ingress.allow-http: "false"
    {{- if .Values.ingress.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}-cert
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: api.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  name: http
    - host: dashboard.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dashboard
                port:
                  name: http
{{- end }}
