{{- if and .Values.ingress.enabled .Values.ingress.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-cert
  labels:
    {{- include "architeq.labels" . | nindent 4 }}
spec:
  domains:
    - api.{{ .Values.global.domain }}
    - app.{{ .Values.global.domain }}
{{- end }}
