from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException

from ..auth import require_api_key
from ..config import public_base_url
from ..models import ApiKey
from ..voices import VOICES, VOICES_BY_ID

router = APIRouter(tags=["voices"])

# Committed preview mp3s (generated by backend/scripts/generate_voice_previews.py).
PREVIEWS_DIR = Path(__file__).resolve().parent.parent / "static" / "voice_previews"


def _previews_on_disk() -> set[str]:
    """Voice ids with a committed sample.

    Read per request (one directory scan, not one stat per voice) so tests can
    repoint PREVIEWS_DIR at runtime.
    """
    return {p.stem for p in PREVIEWS_DIR.glob("*.mp3")}


def _with_preview(voice: dict[str, Any], available: set[str], base: str) -> dict[str, Any]:
    """Fill preview_audio_url when the voice's sample file exists on disk."""
    if voice["voice_id"] not in available:
        return voice
    return {
        **voice,
        "preview_audio_url": f"{base}/static/voice_previews/{voice['voice_id']}.mp3",
    }


@router.get("/list-voices")
async def list_voices(api_key: ApiKey = Depends(require_api_key)):
    available, base = _previews_on_disk(), public_base_url()
    return [_with_preview(v, available, base) for v in VOICES]


@router.get("/get-voice/{voice_id}")
async def get_voice(voice_id: str, api_key: ApiKey = Depends(require_api_key)):
    voice = VOICES_BY_ID.get(voice_id)
    if voice is None:
        raise HTTPException(404, detail="Voice not found")
    return _with_preview(voice, _previews_on_disk(), public_base_url())
