apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "arhiteq.labels" . | nindent 4 }}
    {{- include "arhiteq.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    {{- include "arhiteq.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
