{{- if .Values.serviceAccounts.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.api.name }}
  labels:
    {{- include "arhiteq.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccounts.api.gsaEmail }}
{{- end }}
{{- if .Values.serviceAccounts.worker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.worker.name }}
  labels:
    {{- include "arhiteq.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccounts.worker.gsaEmail }}
{{- end }}
